entities:
  natural_regions:
    surrogate_id: natural_region_id
    columns: ["NaturE", "NaturrEinh", "NaturHaupteinheit"]
    options:
      drop_duplicates: true
    depends_on: []

  location:
    surrogate_id: location_id
    keys: ["Ort", "Kreis", "Land", "Staat", "FlurStr"]
    columns: "include: entities.location.keys"
    unnest:
      id_vars: "include: entities.location.surrogate_id"
      value_vars: "include: entities.location.keys"
      var_name: location_type
      value_name: location_name
    options:
      drop_duplicates: "include: entities.location.keys"
    depends_on: []

  site:
    surrogate_id: site_id
    keys: ["ProjektNr", "Fustel", "EVNr"]
    columns: [
        "ProjektNr",
        "Fustel",
        "EVNr",
        # "Ort",
        # "Kreis",
        # "Land",
        # "Staat",
        # "FlurStr",
        "FustelTyp?",
        "okFustel",
        "Limes",
      ]
    foreign_keys:
      - entity: natural_region
        local_keys: ["NaturE", "NaturrEinh", "NaturHaupteinheit"]
        remote_keys: ["NaturE", "NaturrEinh", "NaturHaupteinheit"]
    options:
      drop_duplicates: "include: entities.site.keys"
    depends_on: ["natural_region"]

  site_type_group:
    surrogate_id: site_type_group_id
    keys: ["OFustelTyp"]
    columns: ["OFustelTyp", "OFustelTyp Beschreibung"]
    options:
      drop_duplicates: True
    depends_on: []

  site_type:
    surrogate_id: site_type_id
    keys: ["FustelTyp", "OFustelTyp"]
    columns: ["FustelTyp", "OFustelTyp", "Fundstellentyp_Beschreibung"]
    options:
      drop_duplicates: "include: entities.site_type.keys"
    foreign_keys:
      - entity: site_type_group
        local_keys: ["OFustelTyp"]
        remote_keys: ["OFustelTyp"]
    depends_on: ["site_type_group"]

  site_site_type:
    surrogate_id: site_site_type_id
    keys: []
    columns: []
    foreign_keys:
      - entity: site_type
        local_keys: "include: entities.site_type.columns"
        remote_keys: "include: entities.site_type.columns"
      - entity: site
        local_keys: "include: entities.site.columns"
        remote_keys: "include: entities.site.columns"
    options:
      drop_duplicates: True
    depends_on: ["site", "site_type"]

  site_location:
    keys: []
    columns:
      [
        "ProjektNr",
        "Fustel",
        "EVNr",
        "Ort",
        "Kreis",
        "Land",
        "Staat",
        "FlurStr",
      ]
    foreign_keys:
      - entity: site
        local_keys: "include: entities.site.columns"
        remote_keys: "include: entities.site.columns"
      - entity: location
        local_keys: ["location_type", "location_name"]
        remote_keys: ["location_type", "location_name"]
    unnest:
      id_vars: "include: entities.site.surrogate_id"
      value_vars: "include: entities.location.keys"
      var_name: location_type
      value_name: location_name
    options:
      drop_duplicates: "include: entities.site_location.keys"
    depends_on: ["site", "location"]

  site_coordinates:
    surrogate_id: site_coordinate_id
    keys: []
    columns: ["Koordinatensystem", "Easting", "Northing", "Höhe"]
    foreign_keys:
      - entity: site
        local_keys: "include: entities.site.keys"
        remote_keys: "include: entities.site.keys"
    options:
      drop_duplicates: True
    depends_on: ["site"]

  site_natural_regions:
    surrogate_id: site_natural_region_id
    keys: []
    columns: []
    foreign_keys:
      - entity: natural_region
        local_keys: "include: entities.natural_regions.columns"
        remote_keys: "include: entities.natural_regions.columns"
      - entity: site
        local_keys: "include: entities.site.columns"
        remote_keys: "include: entities.site.columns"
    options:
      drop_duplicates: "include: entities.site_natural_regions.keys"
    depends_on: ["site", "natural_regions"]

  project:
    surrogate_id: project_id
    keys: ["ProjektNr"]
    columns: ["ProjektNr"]
    foreign_keys:
      - entity: site
        local_keys: ["ProjektNr"]
        remote_keys: ["ProjektNr"]
    options:
      drop_duplicates: true
    depends_on: ["site"]

  taxa:
    surrogate_id: taxon_id
    keys: ["BNam", "TaxAut"]
    columns:
      [
        "PCODE",
        "BNam",
        "Name D",
        "Name_E",
        "Name_F",
        "Name_I",
        "Familie",
        "S_Od",
        "TaxAut",
        "Achtung",
      ]
    options:
      drop_duplicates: true
    depends_on: []

  sample:
    surrogate_id: sample_id
    keys: ["ProjektNr", "Befu", "ProbNr"]
    columns:
      [
        "ProjektNr",
        "Befu",
        "ProbNr",
        # "PCODE", # removed to normalize taxa
        "EDatProb",
        "Strat",
        "Schi",
        "Quadr",
        "Plan",
        "TiefeVon",
        "TiefeBis",
        "Prob_üNN",
        "TK",
        # "ProbTyp",
        # "ProbTyp Beschreibung",
        "Expr1042",
        "SedProb",
        "FlSchn",
        "AblaBdgProb",
        # "ChronoDat",
        # "ChronoDat Beschreibung",
        # "ArchDat",
        # "ArchDat_Beschreibung",
        # "Epoche",
        # "Epochen_Beschreibung",
        # "KultGr",
      ]
    options:
      drop_duplicates: true
    foreign_keys:
      - entity: feature
        local_keys: ["ProjektNr", "Befu"]
        remote_keys: ["ProjektNr", "Befu"]
    depends_on: ["feature"]

  sample_coordinates:
    surrogate_id: sample_coordinate_id
    keys: []
    columns: ["KoordX", "KoordY", "KoordZ"]
    foreign_keys:
      - entity: sample
        local_keys: "include: entities.sample.keys"
        remote_keys: "include: entities.sample.keys"
    options:
      drop_duplicates: True
    depends_on: ["sample"]

  sample_types:
    surrogate_id: sample_type_id
    keys: ["ProbTyp"]
    columns: ["ProbTyp", "ProbTyp Beschreibung"]
    options:
      drop_duplicates: true
    depends_on: []

  sample_sample_type:
    surrogate_id: sample_sample_type_id
    keys: []
    columns: []
    foreign_keys:
      - entity: sample_types
        local_keys: "include: entities.sample_types.keys"
        remote_keys: "include: entities.sample_types.keys"
      - entity: sample
        local_keys: "include: entities.sample.keys"
        remote_keys: "include: entities.sample.keys"
    options:
      drop_duplicates: True
    depends_on: ["sample", "sample_types"]

  sample_processing:
    surrogate_id: sample_processing_id
    columns:
      [
        "ProjektNr",
        "Befu",
        "ProbNr",
        "ORG2,0",
        "ORG1,0",
        "ORG0,5",
        "ORG0,25",
        "MIN2,0",
        "MIN1,0",
        "MIN0,5",
        "MIN0,25",
      ]
    foreign_keys:
      - entity: sample
        local_keys: "include: entities.sample.keys"
        remote_keys: "include: entities.sample.keys"
    unnest:
      id_vars: [""]
      value_vars: "include: entities.location.keys"
      var_name: location_type
      value_name: location_name
    options:
      drop_duplicates: true
    depends_on: ["sample"]

  feature_type:
    surrogate_id: feature_type_id
    keys: ["ProjektNr", "Befu"]
    columns: [ "Befu", "BefuTyp" ]
    options:
      drop_duplicates: true
    foreign_keys:
      - entity: site
        local_keys: "include: entities.site.keys"
        remote_keys: "include: entities.site.keys"
    depends_on: []

  feature:
    surrogate_id: feature_id
    keys: ["ProjektNr", "Befu"]
    columns:
      [
        "ProjektNr",
        "Fustel",
        "EVNr",
        "Befu",
        "BefuTyp",
        "GrJahrBefu",
        "Gebäude",
        "okBefu",
      ]
    options:
      drop_duplicates: true
    foreign_keys:
      - entity: site
        local_keys: "include: entities.site.keys"
        remote_keys: "include: entities.site.keys"
    depends_on: ["site", "feature_type"]

  sample_taxa:
    keys: []
    columns:
      [
        "PCODE",
        "RTyp",
        "RTypGrup",
        "Zust",
        "Zustand",
        "SumFAnzahl",
        "SumFGewicht",
        "geschätzt",
        "SumFFrag",
        "SumPflR",
        "Vorfu",
        "BotBest",
        "BestJa",
        "cf",
        "Anmerkung",
        "BotBear",
      ]
    foreign_keys:
      - entity: sample
        local_keys: "include: entities.sample.keys"
        remote_keys: "include: entities.sample.keys"
      - entity: taxa
        local_keys: "include: entities.taxa.keys"
        remote_keys: "include: entities.taxa.keys"

  archaeological_period:
    surrogate_id: archaeological_period_id
    keys: ["ArchDat", "ArchDat_Beschreibung"]
    columns: ["ArchDat", "ArchDat_Beschreibung"]
    options:
      drop_duplicates: "include: entities.archaeological_period.keys"
    depends_on: []

  sample_archaeological_period:
    surrogate_id: sample_archaeological_period_id
    keys: []
    columns: []
    foreign_keys:
      - entity: archaeological_period
        local_keys: "include: entities.archaeological_period.keys"
        remote_keys: "include: entities.archaeological_period.keys"
      - entity: taxa
        local_keys: "include: entities.taxa.keys"
        remote_keys: "include: entities.taxa.keys"
      - entity: sample
        local_keys: "include: entities.sample.keys"
        remote_keys: "include: entities.sample.keys"
    options:
      drop_duplicates: True
    depends_on: ["sample", "archeaologic_period"]

  chronological_period:
    surrogate_id: chronological_period_id
    keys: ["ChronoDat", "ChronoDat Beschreibung"]
    columns: ["ChronoDat", "ChronoDat Beschreibung"]
    options:
      drop_duplicates: "include: entities.chronological_period.keys"
    depends_on: []

sample_chronological_period:
    surrogate_id: sample_chronological_period_id
    keys: []
    columns: []
    foreign_keys:
      - entity: chronological_period
        local_keys: "include: entities.chronological_period.keys"
        remote_keys: "include: entities.chronological_period.keys"
      - entity: taxa
        local_keys: "include: entities.taxa.keys"
        remote_keys: "include: entities.taxa.keys"
      - entity: sample
        local_keys: "include: entities.sample.keys"
        remote_keys: "include: entities.sample.keys"
    options:
      drop_duplicates: True
    depends_on: ["sample", "chronological_period", "taxa"]

epoch:
  surrogate_id: epoch_id
  keys: ["Epoche", "Epochen_Beschreibung"]
  columns: ["Epoche", "Epochen_Beschreibung"]
  options:
    drop_duplicates: "include: entities.epoch.keys"
  depends_on: []

sample_epoch:
  surrogate_id: sample_epoch_id
  keys: []
  columns: []
  foreign_keys:
    - entity: epoch
      local_keys: "include: entities.epoch.keys"
      remote_keys: "include: entities.epoch.keys"
    - entity: sample
      local_keys: "include: entities.sample.keys"
      remote_keys: "include: entities.sample.keys"
    - entity: taxa
      local_keys: "include: entities.taxa.keys"
      remote_keys: "include: entities.taxa.keys"
  options:
    drop_duplicates: True
  depends_on: ["sample", "epoch", "taxa"]

cultural_groups:
  surrogate_id: cultural_group_id
  keys: ["KultGr"]
  columns: ["KultGr"]
  options:
    drop_duplicates: true
  depends_on: []

sample_cultural_group:
  surrogate_id: sample_cultural_group_id
  keys: []
  columns: []
  foreign_keys:
    - entity: cultural_groups
      local_keys: "include: entities.cultural_groups.keys"
      remote_keys: "include: entities.cultural_groups.keys"
    - entity: sample
      local_keys: "include: entities.sample.keys"
      remote_keys: "include: entities.sample.keys"
    - entity: taxa
      local_keys: "include: entities.taxa.keys"
      remote_keys: "include: entities.taxa.keys"
  options:
    drop_duplicates: True
  depends_on: ["sample", "cultural_groups", "taxa"]

ecocode:
  surrogate_id: ecocode_id
  columns:
    [
      "BNam",
      "TaxAut",
      "L_u",
      "L",
      "T_u",
      "T",
      "K_u",
      "K",
      "F_u",
      "F",
      "F_s",
      "Re_u",
      "Re",
      "N_u",
      "N",
      "S_u",
      "S",
      "SMet",
      "Leb",
      "Bl_u",
      "Bl",
      "G_u",
      "G",
      "Kl_u",
      "Kl",
      "O_u",
      "O",
      "V_u",
      "V",
      "U_u",
      "U",
      "Soz_u",
      "Soz",
      "Ökogruppe",
      "Ökogruppe_u",
      "Dom",
      "Dom_u",
      "WUA",
      "WUE",
      "BLA",
      "BLE",
      "ARE",
      "Zeig",
      "Pio",
      "Roh",
      "WT",
      "SozGrup",
    ]
  options:
    drop_duplicates: ["BNam", "TaxAut"]
  foreign_keys:
    - entity: taxa
      local_keys: "include: entities.taxa.keys"
      remote_keys: "include: entities.taxa.keys"
      drop_duplicates: ["taxon_id"]
    - entity: sample
      local_keys: "include: entities.sample.keys"
      remote_keys: "include: entities.sample.keys"
  depends_on: ["taxa", "sample"]

use_categories:
  surrogate_id: use_category_id
  keys: ["BNam", "TaxAut"]
  columns:
    [
      "BNam",
      "TaxAut",
      "Ge",
      "Hü",
      "Öl",
      "Kp",
      "Imp",
      "Med",
      "Ess",
      "Gar",
      "Nut",
      "M",
      "W",
      "FW",
      "TKG",
    ]
  foreign_keys:
    - entity: taxa
      local_keys: "include: entities.taxa.keys"
      remote_keys: "include: entities.taxa.keys"
      drop_duplicates: ["taxon_id"]
  options:
    drop_duplicates: True
  depends_on: ["taxa"]

contacts:
  # FIXME: unnest authors from multiple columns
  surrogate_id: contact_id
  keys: ["ProjektNr", "ArchAusg", "ArchBear", "BotBear", "Aut"]
  columns: ["ProjektNr", "ArchAusg", "ArchBear", "BotBear", "Aut", "PJahr"]
  options:
    drop_duplicates: "include: entities.contacts.keys"
  foreign_keys:
    - entity: project
      local_keys: "include: entities.project.keys"
      remote_keys: "include: entities.project.keys"
  depends_on: ["project"]

translation:
  ProjektNr: project_number
  Befu: feature_number
  ProbNr: sample_number
  PCODE: sample_code
  BNam: species
  Name D: name_de
  Name_E: name_en
  Name_F: name_fr
  Name_I: name_it
  cf: cf_indicator
  RTyp: remain_type
  RTypGrup: remain_type_group
  Zust: preservation_abbrev
  Zustand: preservation_description
  SumFAnzahl: find_count
  SumFGewicht: find_weight
  geschätzt: is_estimated_count
  SumFFrag: fragment_count
  SumPflR: plant_remain_count
  Anmerkung: species_note
  EDatProb: sampling_date
  Strat: stratigraphy
  Schi: layer
  Quadr: square
  Plan: plan_number
  TiefeVon: depth_from
  TiefeBis: depth_to
  Prob_üNN: elevation_asl_sample
  KoordX: coord_x
  KoordY: coord_y
  KoordZ: coord_z
  AblaBdgProb: is_sample_dry_wet
  ChronoDat: chronological_date
  ChronoDat Beschreibung: chronological_date_description
  Vorfu: is_mass_find
  ArchDat: archeaologic_period
  ArchDat_Beschreibung: archaeological_period_description
  Epoche: epoch
  Epochen_Beschreibung: epoch_description
  KultGr: cultural_group
  ProbTyp: sample_type
  ProbTyp Beschreibung: sample_type_description
  Expr1042: sample_volume
  ORG2,0: organic_2mm
  ORG1,0: organic_1mm
  ORG0,5: organic_0_25mm
  ORG0,25: organic_0_5mm
  MIN2,0: mineral_2mm
  MIN1,0: mineral_1mm
  MIN0,5: mineral_0_25mm
  MIN0,25: mineral_0_5mm
  SedProb: is_subsample_
  FlSchn: flotation_channel
  BefuTyp: feature_type
  GrJahrBefu: construction_year_feature
  FustelTyp: site_type
  Fundstellentyp_Beschreibung: site_type_description
  OFustelTyp: upper_site_type
  OFustelTyp Beschreibung: upper_site_type_description
  FustelTyp?: is_uncertain_site_type
  Gebäude: building
  okBefu: feature_ok
  okErh: preservation_ok
  BotBest: botanical_identification
  BestJa: botanical_identification_year
  Fustel: site_name
  Ort: place
  Kreis: district
  Land: county
  Staat: country
  FlurStr: place_street
  EVNr: site_reference_number
  NaturE: natural_region
  NaturrEinh: natural_region_unit
  NaturHaupteinheit: natural_major_unit
  TK: map_sheet
  Koordinatensystem: coordinate_system
  Easting: easting
  Northing: northing
  Höhe: elevation
  ArchAusg: archaeological_excavator
  ArchBear: archaeological_analyst
  Limes: limes_indicator
  BotBear: botanical_analyst
  Aut: author
  PJahr: publication_year
  okFustel: is_site_ok
  Familie: family
  S_Od: system_order
  TaxAut: taxon_author
  Achtung: warning
  L_u: light_requirement_uncertain
  L: light_requirement
  T_u: temperature_requirement_uncertain
  T: temperature_requirement
  K_u: continentality_uncertain
  K: continentality
  F_u: moisture_uncertain
  F: moisture
  F_s: moisture_special
  Re_u: reaction_uncertain
  Re: reaction
  N_u: nutrients_uncertain
  N: nutrients
  S_u: salt_tolerance_uncertain
  S: salt_tolerance
  SMet: heavy_metal_tolerance
  Leb: life_form
  Bl_u: flowering_time_uncertain
  Bl: flowering_time
  G_u: growth_form_uncertain
  G: growth_form
  Kl_u: vegetation_class_uncertain
  Kl: vegetation_class
  O_u: vegetation_order_uncertain
  O: vegetation_order
  V_u: association_uncertain
  V: association
  U_u: subassociation_uncertain
  U: subassociation
  Soz_u: sociological_group_uncertain
  Soz: sociological_group
  Ökogruppe: ecological_group
  Ökogruppe_u: ecological_group_uncertain
  Dom_u: species_dominance
  Dom: species_dominance_uncertainty
  WUA: weed_indicator
  WUE: weed_indicator_extended
  BLA: leaf_type
  BLE: leaf_habit
  ARE: aridity
  Zeig: indicator_value
  Pio: pioneer
  Roh: ruderal
  WT: water_tolerance
  SozGrup: sociological_group_extended
  Anm: annotation
  Ge: medicinal
  Hü: luxury
  Öl: oil_plant
  Kp: crop_plant
  Imp: imported
  Med: medical_use
  Ess: edible
  Gar: garden_plant
  Nut: useful
  M: male
  W: female
  FW: woody_plant
  TKG: thousand_kernel_weight
